// Generated by CoffeeScript 1.6.3
/*  AppearHandlar
*/


(function() {
  var AppearHandlar;

  AppearHandlar = (function() {
    function AppearHandlar() {
      this.$window = $(window);
      this.nodeList = [];
      this.flag = true;
      this.setEvent();
      this.windowSizeUpdate();
    }

    AppearHandlar.prototype.windowSizeUpdate = function() {
      return this.wh = this.$window.height() * 0.66;
    };

    AppearHandlar.prototype.setAnimation = function(node, before, after, opt) {
      var $node;
      $node = $(node);
      opt = opt || {
        duration: 500,
        easing: 'linear'
      };
      $node.css(before);
      $node.on({
        'scroll::appear': function(e) {
          $node.stop().animate(after, opt);
          return e.stopPropagation();
        },
        'scroll::disappear': function(e) {
          $node.stop().animate(before, opt);
          return e.stopPropagation();
        }
      });
      return this.nodeList.push({
        node: $node,
        offset: $node.offset(),
        isAppeared: false
      });
    };

    AppearHandlar.prototype.setFunction = function(node, before, after) {
      var $node;
      $node = $(node);
      if (typeof before === "function") {
        before($node);
      }
      $node.on({
        'scroll::appear': function(e) {
          if (typeof after === "function") {
            after($node);
          }
          return e.stopPropagation();
        },
        'scroll::disappear': function(e) {
          if (typeof before === "function") {
            before($node);
          }
          return e.stopPropagation();
        }
      });
      return this.nodeList.push({
        node: $node,
        offset: $node.offset(),
        isAppeared: false
      });
    };

    AppearHandlar.prototype.setEvent = function() {
      var _this = this;
      return this.$window.on({
        scroll: function() {
          if (_this.flag) {
            _this.flag = false;
            return setTimeout(function() {
              var item, st, _i, _len, _ref;
              st = _this.$window.scrollTop();
              if (_this.nodeList.length > 0) {
                _ref = _this.nodeList;
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  item = _ref[_i];
                  if (st > item.offset.top - _this.wh) {
                    if (!item.isAppeared) {
                      item.isAppeared = true;
                      item.node.trigger('scroll::appear');
                    }
                  } else if (item.isAppeared) {
                    item.isAppeared = false;
                    item.node.trigger('scroll::disappear');
                  }
                }
              }
              return _this.flag = true;
            }, 500);
          }
        },
        resize: function() {
          return _this.windowSizeUpdate();
        }
      });
    };

    return AppearHandlar;

  })();

  $(function() {
    window.AppearHandlar = new AppearHandlar();
    return $.fn.extend({
      appearAnimate: function(before, after, opt) {
        return this.each(function() {
          return window.AppearHandlar.setAnimation(this, before, after, opt);
        });
      },
      appearFunction: function(before, after) {
        return this.each(function() {
          return window.AppearHandlar.setFunction(this, before, after);
        });
      }
    });
  });

}).call(this);
