// Generated by CoffeeScript 1.7.1

/* !
 * jQuery Appear v1.1
 * https://github.com/kawasako/jquery.appear.js
 *
 * Copyright (c) 2014 Kohei Kawasaki
 * Licensed under the MIT license: http://www.opensource.org/licenses/MIT
 */


/*  AppearHandlar
 */

(function() {
  var AppearHandlar;

  AppearHandlar = (function() {
    function AppearHandlar(timing) {
      this.timing = timing;
      this.$window = $(window);
      this.nodeList = [];
      this.flag = true;
      this.setEvent();
      this.windowSizeUpdate();
    }

    AppearHandlar.prototype.windowSizeUpdate = function() {
      return this.wh = this.$window.height() * this.timing;
    };

    AppearHandlar.prototype.setAnimation = function(node, before, after, opt) {
      var $node;
      $node = $(node);
      opt = opt || {
        duration: 500,
        easing: 'linear'
      };
      $node.css(before);
      $node.on({
        'scroll::appear': function(e) {
          $node.stop().animate(after, opt);
          return e.stopPropagation();
        },
        'scroll::disappear': function(e) {
          $node.stop().animate(before, opt);
          return e.stopPropagation();
        }
      });
      return this.nodeList.push({
        node: $node,
        offset: $node.offset(),
        isAppeared: false
      });
    };

    AppearHandlar.prototype.setFunction = function(node, before, after) {
      var $node;
      $node = $(node);
      if (typeof before === "function") {
        before($node);
      }
      $node.on({
        'scroll::appear': function(e) {
          if (typeof after === "function") {
            after($node);
          }
          return e.stopPropagation();
        },
        'scroll::disappear': function(e) {
          if (typeof before === "function") {
            before($node);
          }
          return e.stopPropagation();
        }
      });
      return this.nodeList.push({
        node: $node,
        offset: $node.offset(),
        isAppeared: false
      });
    };

    AppearHandlar.prototype.setEvent = function() {
      return this.$window.on({
        scroll: (function(_this) {
          return function() {
            if (_this.flag) {
              _this.flag = false;
              return setTimeout(function() {
                var item, st, _i, _len, _ref;
                st = _this.$window.scrollTop();
                if (_this.nodeList.length > 0) {
                  _ref = _this.nodeList;
                  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                    item = _ref[_i];
                    if (st > item.offset.top - _this.wh) {
                      if (!item.isAppeared) {
                        item.isAppeared = true;
                        item.node.trigger('scroll::appear');
                      }
                    } else if (item.isAppeared) {
                      item.isAppeared = false;
                      item.node.trigger('scroll::disappear');
                    }
                  }
                }
                return _this.flag = true;
              }, 40);
            }
          };
        })(this),
        resize: (function(_this) {
          return function() {
            return _this.windowSizeUpdate();
          };
        })(this)
      });
    };

    return AppearHandlar;

  })();

  window.AppearHandlar = AppearHandlar;

  $(function() {
    window.AppearHandlarController = new AppearHandlar(0.5);
    $.fn.extend({
      appearAnimate: function(before, after, opt) {
        return this.each(function() {
          return window.AppearHandlarController.setAnimation(this, before, after, opt);
        });
      },
      appearFunction: function(before, after) {
        return this.each(function() {
          return window.AppearHandlarController.setFunction(this, before, after);
        });
      }
    });
    $('.appear-top').appearAnimate({
      opacity: 0,
      top: -10,
      position: 'relative'
    }, {
      opacity: 1,
      top: 0
    }, {
      duration: 600,
      easing: 'easeOutQuint'
    });
    $('.appear-left').appearAnimate({
      opacity: 0,
      left: -10,
      position: 'relative'
    }, {
      opacity: 1,
      left: 0
    }, {
      duration: 1000,
      easing: 'easeOutQuint'
    });
    $('.appear-right').appearAnimate({
      opacity: 0,
      right: -10,
      position: 'relative'
    }, {
      opacity: 1,
      right: 0
    }, {
      duration: 1000,
      easing: 'easeOutQuint'
    });
    return $('.appear-bottom').appearAnimate({
      opacity: 0,
      bottom: -10,
      position: 'relative'
    }, {
      opacity: 1,
      bottom: 0
    }, {
      duration: 900,
      easing: 'easeInOutQuint'
    });
  });

}).call(this);
